"""Physics-oracle tests for :class:`EwaldMultipoleEnergy`.

These tests pin the *physical* correctness of the LES implementation
beyond the bitwise-vs-oracle parity tests under
``tests/test_molpot/test_les_parity/``. Each test asserts a textbook
quantity that the implementation must reproduce within a stated tolerance:

* **NaCl Madelung constant** — a periodic rocksalt cell with ±1 charges
  must converge to the exact Madelung energy
  ``-M · e² / (4πε₀ · a_nn)``, ``M = 1.7475645946``, in the σ → small
  limit. Tolerance: 0.5 %.

* **Isolated H₂O dipole field** — TIP3P charges placed in a finite cluster
  must produce a field at a far probe point (30 Å) within 1 % of the
  axial-dipole asymptote ``2 |μ| / (4πε₀ · r³)``.

* **Force consistency** — autograd ``F = -∂U/∂r`` must equal the central
  finite-difference of ``U`` over ``Δ = 1e-4 Å`` to within
  ``1e-5 eV/Å``.

* **Translation invariance** of ``U`` to 1e-7 (both paths).

* **Rotation invariance** of ``U`` under simultaneous rotation of
  ``{r, μ, Q}`` to 1e-7.

* **Permutation equivariance** to 1e-9 on CPU.

* **σ-independence at long range** — for two charges at d ≫ σ, ``U(d)``
  must be independent of σ ∈ {0.5, 1.0, 2.0} Å to 1e-5.

* **Self-correction parity toggle** — a single isolated atom with
  ``remove_self_interaction=False`` reproduces the analytic Gaussian
  self-energy ``q² / (σ (2π)^{3/2}) · prefactor``; ``True`` ⇒ 0 exactly.
"""

from __future__ import annotations

import itertools
import math

import numpy as np
import pytest
import torch

from molpot.potentials import EwaldMultipoleEnergy

PREFACTOR = 90.4756  # = 1/(2 ε₀) in eV·Å·e⁻²
NORM_CONST = PREFACTOR / (2.0 * math.pi)  # = 1/(4π ε₀) ≈ 14.3996 eV·Å·e⁻²
MADELUNG_NACL = 1.7475645946  # Kittel, *Introduction to Solid State Physics*, 8th ed., Table 3.1


# ---------------------------------------------------------------------------
# NaCl Madelung
# ---------------------------------------------------------------------------


def _build_nacl_supercell(a: float = 5.64) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Standard NaCl rocksalt: 4 Na + 4 Cl at FCC sublattices in a cubic cell.

    Args:
        a: Cubic lattice parameter in Å. Default 5.64 (experimental NaCl).

    Returns:
        ``(positions (8,3), charges (8,), cell (3,3))`` — Na sites at FCC
        of the cube, Cl sites at FCC offset by ``(a/2, 0, 0)``. Nearest
        Na-Cl distance ``a/2`` is the Madelung length scale ``R₀``.
    """
    fcc_basis = torch.tensor(
        [
            [0.0, 0.0, 0.0],
            [0.0, 0.5, 0.5],
            [0.5, 0.0, 0.5],
            [0.5, 0.5, 0.0],
        ],
        dtype=torch.float64,
    )
    na_pos = fcc_basis * a
    cl_pos = (fcc_basis + torch.tensor([0.5, 0.0, 0.0], dtype=torch.float64)) * a
    pos = torch.cat([na_pos, cl_pos], dim=0)
    charges = torch.cat([torch.ones(4), -torch.ones(4)]).to(torch.float64)
    cell = a * torch.eye(3, dtype=torch.float64)
    return pos, charges, cell


def test_nacl_madelung_converges() -> None:
    """Per-ion energy → ``-M · e² / (4πε₀ · a)`` within 0.5 %.

    The Ewald sum ``½ Σᵢ qᵢ Φ(rᵢ)`` halves the Madelung double-count, so
    per-ion energy is ``-M·e²/(4πε₀·a) = -M·e²/(4πε₀·2R₀)``, where
    ``a`` is the cubic lattice parameter and ``R₀ = a/2`` is the
    nearest-neighbor Na-Cl distance.
    """
    a = 5.64  # Å — experimental NaCl lattice parameter
    pos, q, cell = _build_nacl_supercell(a)

    # Tight σ + dl. σ=0.3 Å is small enough that the screened kernel is
    # nearly bare 1/r at R0 = 2.82 Å (erf(2.82/(0.3·√2)) ≈ 1.0); dl=0.4 Å
    # gives k_max ≈ 15.7 Å⁻¹ and reciprocal-mode count ~1300, plenty for
    # 8-atom convergence to the 0.5 % gate.
    pot = EwaldMultipoleEnergy(sigma=0.3, dl=0.4, prefactor=PREFACTOR)
    out = pot.forward(q=q, pos=pos, cell=cell)

    energy_total = float(out["pot"])
    energy_per_ion = energy_total / 8.0
    expected_per_ion = -MADELUNG_NACL * NORM_CONST / a
    rel_err = abs(energy_per_ion - expected_per_ion) / abs(expected_per_ion)

    assert rel_err < 5e-3, (
        f"NaCl Madelung: per-ion {energy_per_ion:.5f} eV vs "
        f"analytic {expected_per_ion:.5f} eV, rel_err {rel_err:.2e}"
    )


# ---------------------------------------------------------------------------
# Isolated H₂O dipole field
# ---------------------------------------------------------------------------


def _build_water_with_probe(probe_r: float = 30.0) -> tuple[torch.Tensor, torch.Tensor]:
    """TIP3P water with a fictional zero-charge ghost atom at probe distance.

    The probe atom carries q=0, so the per-atom field at its position is
    exactly the field generated by the three real water atoms.
    """
    # TIP3P geometry (Å): O at origin, two H's at the 104.52° angle.
    half_angle = math.radians(104.52 / 2.0)
    OH = 0.9572  # Å
    pos = torch.tensor(
        [
            [0.0, 0.0, 0.0],  # O
            [OH * math.sin(half_angle), 0.0, OH * math.cos(half_angle)],  # H1
            [-OH * math.sin(half_angle), 0.0, OH * math.cos(half_angle)],  # H2
            [0.0, 0.0, probe_r],  # ghost probe
        ],
        dtype=torch.float64,
    )
    # TIP3P partial charges
    q = torch.tensor([-0.834, 0.417, 0.417, 0.0], dtype=torch.float64)
    return pos, q


def test_isolated_water_dipole_field_at_30_angstroms() -> None:
    """Field at ghost probe 30 Å away matches dipole asymptote within 1 %."""
    probe_r = 30.0
    pos, q = _build_water_with_probe(probe_r=probe_r)

    pot = EwaldMultipoleEnergy(sigma=0.3, prefactor=PREFACTOR)
    out = pot.forward(q=q, pos=pos, cell=None)

    field_at_probe = out["field"][3]  # (3,) — field at the ghost atom
    field_z = float(field_at_probe[2])

    # Compute the molecular dipole moment from charges (origin-independent
    # only for neutral systems — TIP3P is exactly neutral).
    mu_mol = (q.unsqueeze(-1) * pos).sum(dim=0)  # (3,)
    mu_norm = float(mu_mol.norm())  # in e·Å
    # Axial-dipole field magnitude: 2|μ|/(4πε₀·r³).
    expected_field_mag = 2.0 * mu_norm * NORM_CONST / probe_r**3

    # The probe sits along +z; the dipole points along +z (negative oxygen
    # at origin, positive H's at +z). Field along the dipole axis at +z
    # has the same sign as the dipole.
    rel_err = abs(field_z - expected_field_mag) / expected_field_mag
    assert rel_err < 1e-2, (
        f"H₂O probe field {field_z:.4e} V/Å vs dipole asymptote "
        f"{expected_field_mag:.4e}, rel_err {rel_err:.2e}"
    )


# ---------------------------------------------------------------------------
# Force consistency (autograd vs central finite-difference)
# ---------------------------------------------------------------------------


def test_autograd_forces_match_finite_difference() -> None:
    """``F_auto = -∂U/∂r`` must agree with central FD to 1e-5 eV/Å."""
    rng = np.random.default_rng(0)
    n = 8
    pos_np = rng.uniform(-3.0, 3.0, size=(n, 3))
    q_np = rng.standard_normal(n)
    q_np -= q_np.mean()  # neutralise

    pos = torch.from_numpy(pos_np).to(torch.float64).requires_grad_(True)
    q = torch.from_numpy(q_np).to(torch.float64)

    pot_module = EwaldMultipoleEnergy(sigma=1.0, prefactor=PREFACTOR)
    out = pot_module.forward(q=q, pos=pos, cell=None)
    energy = out["pot"]
    (grad,) = torch.autograd.grad(energy, pos, create_graph=False)
    f_auto = -grad

    # Central finite difference, Δ = 1e-4 Å
    delta = 1e-4
    f_fd = torch.zeros_like(pos)
    pos_detached = pos.detach().clone()
    for i, c in itertools.product(range(n), range(3)):
        plus = pos_detached.clone()
        plus[i, c] += delta
        u_plus = pot_module.forward(q=q, pos=plus, cell=None)["pot"].item()
        minus = pos_detached.clone()
        minus[i, c] -= delta
        u_minus = pot_module.forward(q=q, pos=minus, cell=None)["pot"].item()
        f_fd[i, c] = -(u_plus - u_minus) / (2 * delta)

    max_err = float((f_auto - f_fd).abs().max())
    assert max_err < 1e-5, f"max force error {max_err:.3e} eV/Å (FD vs autograd)"


def _synthetic_periodic_inputs(
    seed: int = 0,
    n: int = 6,
    L: float = 10.0,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """Build deterministic float64 (pos, q, μ, Q, cell) for FD tests.

    The cell is a slightly anisotropic axis-aligned box (no near-equal
    axis lengths) with ``L = 10 Å``; with the default ``dl = 2 Å`` this
    keeps every reciprocal k-vector at least ~2 % away from the
    cutoff sphere ``k² = (π)²``, so even without the frozen-grid path
    rotation invariance is solid. Charges are exactly neutral and the
    quadrupoles are symmetric and traceless (the two algebraic
    contracts ``EwaldMultipoleEnergy`` requires).
    """
    rng = np.random.default_rng(seed)
    pos = torch.from_numpy(rng.uniform(0.5, L - 0.5, size=(n, 3))).to(torch.float64)
    q_np = rng.standard_normal(n)
    q_np -= q_np.mean()  # neutralise (algebraic identity from PermMultipoleHead)
    q = torch.from_numpy(q_np).to(torch.float64)
    mu = torch.from_numpy(rng.uniform(-0.3, 0.3, size=(n, 3))).to(torch.float64)
    # Build a symmetric traceless (N, 3, 3) Q tensor. M = (M + Mᵀ)/2 - tr/3 · I.
    Q_full = torch.from_numpy(rng.uniform(-0.2, 0.2, size=(n, 3, 3))).to(torch.float64)
    Q_sym = 0.5 * (Q_full + Q_full.transpose(-1, -2))
    Q_trace = torch.einsum("nii->n", Q_sym)
    Q = Q_sym - (Q_trace / 3.0).unsqueeze(-1).unsqueeze(-1) * torch.eye(3, dtype=torch.float64)
    cell = torch.tensor(
        [[L, 0.0, 0.0], [0.0, L * 1.05, 0.0], [0.0, 0.0, L * 0.95]],
        dtype=torch.float64,
    )
    return pos, q, mu, Q, cell


def test_periodic_force_fd_synthetic_multipoles_frozen_grid() -> None:
    """Strict autograd-vs-FD agreement on Ewald-only with synthetic multipoles.

    Pins the contract that the periodic Ewald path is differentiable
    in atom positions to ``≤ 1e-5 eV/Å`` (central FD, ``dh = 1e-4 Å``).
    Position FD does not change the cell, so this test passes with or
    without the frozen-grid hook — but we exercise the
    ``kvec_indices`` path here as well so a regression to the frozen
    path is caught alongside the production path.
    """
    pos, q, mu, Q, cell = _synthetic_periodic_inputs(seed=0)
    pot = EwaldMultipoleEnergy(sigma=1.0, dl=2.0, prefactor=PREFACTOR)
    nvec = pot.enumerate_kvec_indices(cell)

    pos_grad = pos.detach().requires_grad_(True)
    out = pot.forward(q=q, pos=pos_grad, cell=cell, mu=mu, Q=Q, kvec_indices=nvec)
    energy = out["pot"]
    (grad,) = torch.autograd.grad(energy, pos_grad, create_graph=False)
    f_auto = -grad

    delta = 1e-4
    f_fd = torch.zeros_like(pos)
    for i, c in itertools.product(range(pos.shape[0]), range(3)):
        plus = pos.clone()
        plus[i, c] += delta
        u_plus = pot.forward(q=q, pos=plus, cell=cell, mu=mu, Q=Q, kvec_indices=nvec)["pot"].item()
        minus = pos.clone()
        minus[i, c] -= delta
        u_minus = pot.forward(q=q, pos=minus, cell=cell, mu=mu, Q=Q, kvec_indices=nvec)[
            "pot"
        ].item()
        f_fd[i, c] = -(u_plus - u_minus) / (2 * delta)

    max_err = float((f_auto - f_fd).abs().max())
    assert max_err < 1e-5, f"max force error {max_err:.3e} eV/Å (FD vs autograd)"


def test_periodic_stress_fd_synthetic_multipoles_frozen_grid() -> None:
    """Strict autograd-vs-FD agreement on Ewald-only stress under cell strain.

    Uses the frozen-grid path (``kvec_indices`` taken once on the
    unperturbed cell) so the ``keep = k² ≤ k_sq_max`` step
    discontinuity does not enter the FD difference. Without this, FD
    diverges from autograd by O(1) when the FD step crosses a
    boundary k-vector; with this, the cell-strain derivative is a
    smooth function of strain and FD agrees to ``1e-5`` relative.

    This is the canonical PME / Ewald FD-stress technique — see
    LAMMPS ``fix_numdiff_virial`` for the public statement of the
    underlying numerical hazard.
    """
    pos, q, mu, Q, cell = _synthetic_periodic_inputs(seed=1)
    pot = EwaldMultipoleEnergy(sigma=1.0, dl=2.0, prefactor=PREFACTOR)
    nvec = pot.enumerate_kvec_indices(cell)

    # Autograd stress via differentiable strain: pos → (I + ε)·pos,
    # cell → (I + ε)·cell.
    eye3 = torch.eye(3, dtype=torch.float64)
    strain = torch.zeros(3, 3, dtype=torch.float64, requires_grad=True)
    sym_eps = 0.5 * (strain + strain.transpose(-1, -2))
    I_plus = eye3 + sym_eps
    pos_eps = pos @ I_plus.T
    cell_eps = I_plus @ cell

    out = pot.forward(q=q, pos=pos_eps, cell=cell_eps, mu=mu, Q=Q, kvec_indices=nvec)
    energy = out["pot"]
    V = float(torch.linalg.det(cell).abs())
    (stress_eps,) = torch.autograd.grad(energy, strain, create_graph=False)
    # Symmetric strain convention (off-diagonal counts ε_αβ = ε_βα as one
    # variable): doubles off-diagonal autograd, leaves diagonal alone.
    stress_eps_sym = stress_eps + stress_eps.T - torch.diag_embed(torch.diagonal(stress_eps))
    sigma_auto = stress_eps_sym / V

    # Central FD over each independent symmetric component (a ≤ b).
    dh = 1e-4
    sigma_fd = torch.zeros(3, 3, dtype=torch.float64)
    for a in range(3):
        for b in range(a, 3):
            eps_p = torch.zeros(3, 3, dtype=torch.float64)
            eps_p[a, b] = dh
            eps_p[b, a] = dh
            I_p = eye3 + eps_p
            I_m = eye3 - eps_p

            E_plus = pot.forward(
                q=q,
                pos=pos @ I_p.T,
                cell=I_p @ cell,
                mu=mu,
                Q=Q,
                kvec_indices=nvec,
            )["pot"].item()
            E_minus = pot.forward(
                q=q,
                pos=pos @ I_m.T,
                cell=I_m @ cell,
                mu=mu,
                Q=Q,
                kvec_indices=nvec,
            )["pot"].item()
            sigma_fd[a, b] = (E_plus - E_minus) / (2.0 * dh) / V
            sigma_fd[b, a] = sigma_fd[a, b]

    # Relative error on components meaningfully above noise.
    mask = sigma_fd.abs() > 1e-6
    rel = (sigma_auto - sigma_fd).abs() / sigma_fd.abs().clamp(min=1e-12)
    worst = float(rel[mask].max()) if mask.any() else 0.0
    assert worst < 1e-5, (
        f"max relative stress error = {worst:.3e}\nσ_auto = {sigma_auto}\nσ_fd   = {sigma_fd}"
    )


def test_periodic_stress_dynamic_grid_fails_without_freeze() -> None:
    """Documents *why* the frozen-grid path is required for FD-stress.

    Repeats the above check but uses the production dynamic-grid path
    (``kvec_indices=None``). FD straddles the discrete ``keep`` flip
    at the Ewald cutoff and disagrees with autograd by O(0.1)–O(1) on
    typical small unit cells. We assert that the disagreement is
    *measurable* — if a future refactor makes the production path
    smooth, this test should fail and be deleted (the new strict
    test would already cover the contract).
    """
    pos, q, mu, Q, cell = _synthetic_periodic_inputs(seed=1)
    pot = EwaldMultipoleEnergy(sigma=1.0, dl=2.0, prefactor=PREFACTOR)

    eye3 = torch.eye(3, dtype=torch.float64)
    strain = torch.zeros(3, 3, dtype=torch.float64, requires_grad=True)
    sym_eps = 0.5 * (strain + strain.transpose(-1, -2))
    I_plus = eye3 + sym_eps
    pos_eps = pos @ I_plus.T
    cell_eps = I_plus @ cell

    out = pot.forward(q=q, pos=pos_eps, cell=cell_eps, mu=mu, Q=Q)
    energy = out["pot"]
    V = float(torch.linalg.det(cell).abs())
    (stress_eps,) = torch.autograd.grad(energy, strain, create_graph=False)
    stress_eps_sym = stress_eps + stress_eps.T - torch.diag_embed(torch.diagonal(stress_eps))
    sigma_auto = stress_eps_sym / V

    dh = 1e-4
    sigma_fd = torch.zeros(3, 3, dtype=torch.float64)
    for a in range(3):
        for b in range(a, 3):
            eps_p = torch.zeros(3, 3, dtype=torch.float64)
            eps_p[a, b] = dh
            eps_p[b, a] = dh
            I_p = eye3 + eps_p
            I_m = eye3 - eps_p
            E_plus = pot.forward(q=q, pos=pos @ I_p.T, cell=I_p @ cell, mu=mu, Q=Q)["pot"].item()
            E_minus = pot.forward(q=q, pos=pos @ I_m.T, cell=I_m @ cell, mu=mu, Q=Q)["pot"].item()
            sigma_fd[a, b] = (E_plus - E_minus) / (2.0 * dh) / V
            sigma_fd[b, a] = sigma_fd[a, b]

    mask = sigma_fd.abs() > 1e-6
    rel = (sigma_auto - sigma_fd).abs() / sigma_fd.abs().clamp(min=1e-12)
    worst = float(rel[mask].max()) if mask.any() else 0.0
    # Negative assertion: documents that the dynamic-grid path is
    # *not* FD-smooth. If this ever passes ``< 1e-3``, switch to the
    # strict frozen-grid test above and delete this one.
    assert worst > 1e-3, (
        f"dynamic-grid FD-stress agrees within {worst:.3e}; "
        "production path appears now-smooth — replace this test with "
        "the strict frozen-grid contract above."
    )


# ---------------------------------------------------------------------------
# Symmetries
# ---------------------------------------------------------------------------


def _random_neutral_charges(rng: np.random.Generator, n: int) -> torch.Tensor:
    q = rng.standard_normal(n)
    q -= q.mean()
    return torch.from_numpy(q).to(torch.float64)


def test_translation_invariance_realspace() -> None:
    rng = np.random.default_rng(1)
    pos = torch.from_numpy(rng.uniform(-3.0, 3.0, size=(6, 3))).to(torch.float64)
    q = _random_neutral_charges(rng, 6)
    pot = EwaldMultipoleEnergy(sigma=1.0, prefactor=PREFACTOR)
    u0 = pot.forward(q=q, pos=pos, cell=None)["pot"].item()
    t = torch.tensor([2.5, -1.7, 3.1], dtype=torch.float64)
    u1 = pot.forward(q=q, pos=pos + t, cell=None)["pot"].item()
    assert abs(u0 - u1) < 1e-7, f"translation: U0={u0}, U1={u1}, diff={abs(u0 - u1)}"


def test_translation_invariance_reciprocal() -> None:
    rng = np.random.default_rng(2)
    L = 12.0
    pos = torch.from_numpy(rng.uniform(0.0, L, size=(8, 3))).to(torch.float64)
    q = _random_neutral_charges(rng, 8)
    cell = L * torch.eye(3, dtype=torch.float64)
    pot = EwaldMultipoleEnergy(sigma=1.0, dl=2.0, prefactor=PREFACTOR)
    u0 = pot.forward(q=q, pos=pos, cell=cell)["pot"].item()
    t = torch.tensor([2.5, -1.7, 3.1], dtype=torch.float64)
    u1 = pot.forward(q=q, pos=pos + t, cell=cell)["pot"].item()
    assert abs(u0 - u1) < 1e-7, f"translation: U0={u0}, U1={u1}, diff={abs(u0 - u1)}"


def _random_rotation_matrix(seed: int) -> torch.Tensor:
    """Random SO(3) matrix via QR decomposition of a random Gaussian matrix."""
    rng = np.random.default_rng(seed)
    A = rng.standard_normal((3, 3))
    Q, R = np.linalg.qr(A)
    Q = Q @ np.diag(np.sign(np.diag(R)))
    if np.linalg.det(Q) < 0:
        Q[:, 0] = -Q[:, 0]
    return torch.from_numpy(Q).to(torch.float64)


def test_rotation_invariance_realspace() -> None:
    rng = np.random.default_rng(3)
    pos = torch.from_numpy(rng.uniform(-3.0, 3.0, size=(6, 3))).to(torch.float64)
    q = _random_neutral_charges(rng, 6)
    mu = torch.from_numpy(rng.standard_normal((6, 3))).to(torch.float64)
    pot = EwaldMultipoleEnergy(sigma=1.0, prefactor=PREFACTOR)

    u0 = pot.forward(q=q, pos=pos, mu=mu, cell=None)["pot"].item()
    R = _random_rotation_matrix(seed=10)
    pos_rot = pos @ R.T
    mu_rot = mu @ R.T
    u1 = pot.forward(q=q, pos=pos_rot, mu=mu_rot, cell=None)["pot"].item()
    assert abs(u0 - u1) < 1e-7, f"rotation: U0={u0}, U1={u1}"


def test_permutation_equivariance() -> None:
    rng = np.random.default_rng(4)
    n = 5
    pos = torch.from_numpy(rng.uniform(-3.0, 3.0, size=(n, 3))).to(torch.float64)
    q = _random_neutral_charges(rng, n)
    pot = EwaldMultipoleEnergy(sigma=1.0, prefactor=PREFACTOR)

    perm = torch.randperm(n, generator=torch.Generator().manual_seed(7))
    u0 = pot.forward(q=q, pos=pos, cell=None)["pot"].item()
    u1 = pot.forward(q=q[perm], pos=pos[perm], cell=None)["pot"].item()
    assert abs(u0 - u1) < 1e-9, f"permutation: U0={u0}, U1={u1}, diff={abs(u0 - u1)}"


# ---------------------------------------------------------------------------
# σ-independence at long range
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("sigma", [0.5, 1.0, 2.0])
def test_sigma_independence_at_long_range(sigma: float) -> None:
    """Two charges at d ≫ σ must give same U across σ to 1e-5."""
    pos = torch.tensor([[0.0, 0.0, 0.0], [15.0, 0.0, 0.0]], dtype=torch.float64)
    q = torch.tensor([1.0, -1.0], dtype=torch.float64)
    pot = EwaldMultipoleEnergy(sigma=sigma, prefactor=PREFACTOR)
    out = pot.forward(q=q, pos=pos, cell=None)
    expected = -NORM_CONST / 15.0  # bare Coulomb at long range
    assert abs(float(out["pot"]) - expected) < 1e-5, (
        f"σ={sigma}: U={float(out['pot'])} vs {expected}"
    )


# ---------------------------------------------------------------------------
# Self-correction parity toggle
# ---------------------------------------------------------------------------


def test_single_atom_self_interaction_toggle() -> None:
    """Single isolated atom: RSI=True ⇒ U=0; RSI=False ⇒ analytic self-energy."""
    pos = torch.tensor([[0.0, 0.0, 0.0]], dtype=torch.float64)
    q = torch.tensor([1.0], dtype=torch.float64)

    pot_true = EwaldMultipoleEnergy(sigma=1.0, prefactor=PREFACTOR, remove_self_interaction=True)
    u_true = float(pot_true.forward(q=q, pos=pos, cell=None)["pot"])
    assert abs(u_true) < 1e-12, f"RSI=True should give zero, got {u_true}"

    pot_false = EwaldMultipoleEnergy(sigma=1.0, prefactor=PREFACTOR, remove_self_interaction=False)
    u_false = float(pot_false.forward(q=q, pos=pos, cell=None)["pot"])
    expected = PREFACTOR / ((2.0 * math.pi) ** 1.5)  # 1²/(σ·(2π)^{3/2}) · prefactor with σ=1
    assert abs(u_false - expected) < 1e-12, f"RSI=False: {u_false} vs analytic {expected}"


# ---------------------------------------------------------------------------
# Full SO(3) equivariance — energy invariance + field/quantity equivariance
#
# Under a rotation R applied jointly to {pos, μ, Q, cell}:
#   pos    → R pos      (vector)
#   μ      → R μ        (vector)
#   Q      → R Q Rᵀ     (rank-2 symmetric tensor)
#   cell   → cell Rᵀ    (lattice vectors transform like positions)
#   U      = U          (scalar — invariant)
#   φ(rᵢ)  = φ_orig(rᵢ) (scalar field at atom — invariant)
#   E(rᵢ)  → R E_orig(rᵢ)  (vector field at atom — equivariant)
#
# Tolerance is 1e-9 for invariants (algebraic identity in float64) and
# 1e-9 for equivariance after re-rotating the original field back.
# ---------------------------------------------------------------------------


def _rotate_quadrupole(Q: torch.Tensor, R: torch.Tensor) -> torch.Tensor:
    """``Q[n] → R · Q[n] · Rᵀ`` for a rank-2 tensor stored as ``(N, 3, 3)``."""
    return torch.einsum("ab,nbc,dc->nad", R, Q, R)


def _random_traceless_symmetric_Q(rng: np.random.Generator, n: int) -> torch.Tensor:
    raw = rng.standard_normal((n, 3, 3))
    sym = 0.5 * (raw + raw.transpose(0, 2, 1))
    trace_per_atom = np.einsum("nii->n", sym)
    Q_traceless = sym - (trace_per_atom / 3.0)[:, None, None] * np.eye(3)[None, :, :]
    return torch.from_numpy(Q_traceless).to(torch.float64)


class TestSO3Equivariance:
    """Joint rotation of {pos, μ, Q, cell} leaves U invariant and rotates E."""

    def test_realspace_full_multipole(self) -> None:
        rng = np.random.default_rng(7)
        n = 6
        pos = torch.from_numpy(rng.uniform(-3.0, 3.0, size=(n, 3))).to(torch.float64)
        q = _random_neutral_charges(rng, n)
        mu = torch.from_numpy(rng.standard_normal((n, 3))).to(torch.float64)
        Q = _random_traceless_symmetric_Q(rng, n)
        pot = EwaldMultipoleEnergy(sigma=1.0, prefactor=PREFACTOR)

        ref = pot.forward(q=q, pos=pos, mu=mu, Q=Q, cell=None)
        R = _random_rotation_matrix(seed=11)
        rot = pot.forward(
            q=q,
            pos=pos @ R.T,
            mu=mu @ R.T,
            Q=_rotate_quadrupole(Q, R),
            cell=None,
        )

        # Energy invariant
        assert abs(float(ref["pot"]) - float(rot["pot"])) < 1e-9, (
            f"realspace U not invariant under SO(3): "
            f"ref={float(ref['pot'])}, rot={float(rot['pot'])}"
        )
        # phi invariant at each atom (atom-by-atom — atoms don't reorder)
        torch.testing.assert_close(ref["phi"], rot["phi"], atol=1e-9, rtol=1e-9)
        # field equivariant: rot.field[i] = R · ref.field[i]
        torch.testing.assert_close(ref["field"] @ R.T, rot["field"], atol=1e-9, rtol=1e-9)

    def test_reciprocal_full_multipole(self) -> None:
        rng = np.random.default_rng(8)
        L = 10.0
        n = 8
        pos = torch.from_numpy(rng.uniform(0.0, L, size=(n, 3))).to(torch.float64)
        q = _random_neutral_charges(rng, n)
        mu = torch.from_numpy(rng.standard_normal((n, 3))).to(torch.float64)
        Q = _random_traceless_symmetric_Q(rng, n)
        cell = L * torch.eye(3, dtype=torch.float64)
        pot = EwaldMultipoleEnergy(sigma=1.0, dl=2.0, prefactor=PREFACTOR)

        ref = pot.forward(q=q, pos=pos, mu=mu, Q=Q, cell=cell)
        R = _random_rotation_matrix(seed=12)
        rot = pot.forward(
            q=q,
            pos=pos @ R.T,
            mu=mu @ R.T,
            Q=_rotate_quadrupole(Q, R),
            cell=cell @ R.T,  # lattice vectors rotate with positions
        )

        # k-grid resolution is dl-quantized so reciprocal SO(3) is a soft
        # 1e-6, not the algebraic 1e-9 of realspace; mode count differs
        # across orientations.
        assert abs(float(ref["pot"]) - float(rot["pot"])) < 1e-6, (
            f"reciprocal U not invariant under SO(3): "
            f"ref={float(ref['pot'])}, rot={float(rot['pot'])}"
        )
        torch.testing.assert_close(ref["phi"], rot["phi"], atol=1e-6, rtol=1e-6)
        torch.testing.assert_close(ref["field"] @ R.T, rot["field"], atol=1e-6, rtol=1e-6)

    def test_induced_response_equivariance(self) -> None:
        """``q_induced`` invariant; ``u_induced`` equivariant. Realspace path."""
        rng = np.random.default_rng(9)
        n = 5
        pos = torch.from_numpy(rng.uniform(-3.0, 3.0, size=(n, 3))).to(torch.float64)
        q = _random_neutral_charges(rng, n)
        kappa = torch.from_numpy(np.abs(rng.standard_normal(n)) + 0.1).to(torch.float64)
        alpha = torch.from_numpy(np.abs(rng.standard_normal(n)) + 0.1).to(torch.float64)
        pot = EwaldMultipoleEnergy(sigma=1.0, prefactor=PREFACTOR)

        ref = pot.forward(q=q, pos=pos, kappa=kappa, alpha=alpha, cell=None)
        R = _random_rotation_matrix(seed=13)
        rot = pot.forward(q=q, pos=pos @ R.T, kappa=kappa, alpha=alpha, cell=None)

        # q_induced = -κ · φ; both κ and φ are scalars, so invariant.
        torch.testing.assert_close(ref["q_induced"], rot["q_induced"], atol=1e-9, rtol=1e-9)
        # u_induced = α · E; α scalar, E rotates, so u_induced rotates too.
        torch.testing.assert_close(ref["u_induced"] @ R.T, rot["u_induced"], atol=1e-9, rtol=1e-9)


# ---------------------------------------------------------------------------
# torch.compile round-trip
#
# `EwaldMultipoleEnergy.forward` uses Python control flow (`for raw in
# unique`, `if cell is None`) and `.item()` calls (Nk[i], unique batch
# index), all of which force graph breaks under `torch.compile`. With
# `fullgraph=False` the compile must still execute and produce
# numerically-equivalent output — that's the contract this test pins.
# ---------------------------------------------------------------------------


class TestTorchCompile:
    @pytest.fixture(scope="class")
    def realspace_inputs(self):
        rng = np.random.default_rng(101)
        pos = torch.from_numpy(rng.uniform(-3.0, 3.0, size=(6, 3))).to(torch.float64)
        q = _random_neutral_charges(rng, 6)
        mu = torch.from_numpy(rng.standard_normal((6, 3))).to(torch.float64)
        return q, pos, mu

    def test_compile_realspace(self, realspace_inputs) -> None:
        """Compiled forward must match eager on the realspace path."""
        q, pos, mu = realspace_inputs
        pot = EwaldMultipoleEnergy(sigma=1.0, prefactor=PREFACTOR)

        eager = pot.forward(q=q, pos=pos, mu=mu, cell=None)

        compiled = torch.compile(pot.forward, fullgraph=False, dynamic=False)
        compiled_out = compiled(q=q, pos=pos, mu=mu, cell=None)

        torch.testing.assert_close(eager["pot"], compiled_out["pot"], atol=1e-10, rtol=1e-10)
        torch.testing.assert_close(eager["phi"], compiled_out["phi"], atol=1e-10, rtol=1e-10)
        torch.testing.assert_close(eager["field"], compiled_out["field"], atol=1e-10, rtol=1e-10)

    def test_compile_reciprocal(self) -> None:
        """Compiled forward must match eager on the reciprocal path."""
        rng = np.random.default_rng(102)
        L = 10.0
        n = 6
        pos = torch.from_numpy(rng.uniform(0.0, L, size=(n, 3))).to(torch.float64)
        q = _random_neutral_charges(rng, n)
        cell = L * torch.eye(3, dtype=torch.float64)
        pot = EwaldMultipoleEnergy(sigma=1.0, dl=2.0, prefactor=PREFACTOR)

        eager = pot.forward(q=q, pos=pos, cell=cell)

        compiled = torch.compile(pot.forward, fullgraph=False, dynamic=False)
        compiled_out = compiled(q=q, pos=pos, cell=cell)

        torch.testing.assert_close(eager["pot"], compiled_out["pot"], atol=1e-10, rtol=1e-10)
        torch.testing.assert_close(eager["phi"], compiled_out["phi"], atol=1e-10, rtol=1e-10)
        torch.testing.assert_close(eager["field"], compiled_out["field"], atol=1e-10, rtol=1e-10)

    def test_compile_with_induced_response(self, realspace_inputs) -> None:
        """Compiled forward must preserve the κ/α inline response."""
        q, pos, _mu = realspace_inputs
        rng = np.random.default_rng(103)
        kappa = torch.from_numpy(np.abs(rng.standard_normal(6)) + 0.1).to(torch.float64)
        alpha = torch.from_numpy(np.abs(rng.standard_normal(6)) + 0.1).to(torch.float64)
        pot = EwaldMultipoleEnergy(sigma=1.0, prefactor=PREFACTOR)

        eager = pot.forward(q=q, pos=pos, kappa=kappa, alpha=alpha, cell=None)
        compiled = torch.compile(pot.forward, fullgraph=False, dynamic=False)
        compiled_out = compiled(q=q, pos=pos, kappa=kappa, alpha=alpha, cell=None)

        torch.testing.assert_close(eager["pot"], compiled_out["pot"], atol=1e-10, rtol=1e-10)
        torch.testing.assert_close(
            eager["q_induced"],
            compiled_out["q_induced"],
            atol=1e-10,
            rtol=1e-10,
        )
        torch.testing.assert_close(
            eager["u_induced"],
            compiled_out["u_induced"],
            atol=1e-10,
            rtol=1e-10,
        )
